In [1]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import math as math
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [58]:
iris = load_iris(as_frame=True)

In [59]:
iris_frame = pd.DataFrame(iris.data)
# Делаем имена колонок такие же, как имена переменных:
iris_frame.columns = iris.feature_names
# Добавляем столбец с целевой переменной: 
iris_frame['target'] = iris.target
# Для наглядности добавляем столбец с сортами: 
iris_frame['name'] = iris_frame.target.apply(lambda x : iris.target_names[x])
#удаляем третий класс setosa
iris_frame = iris_frame.loc[(iris_frame['name'] != 'setosa')]
# Смотрим, что получилось:
iris_frame

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
52                 6.9               3.1                4.9               1.5   
53                 5.5               2.3                4.0               1.3   
54                 6.5               2.8                4.6               1.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target        name  
50        1  versicolor  
51        1  versicolor  
52        1  versicolor  
53        1  versicolor  
54        1  versicolor  
..      ...         ...  
145       2   virginica  
146       2   virginica  
147       2   virginica  
148       2   virginica  
149       2   virginica  

[100 rows x 6 columns]

In [60]:
iris_frame['target'].replace({1: 0, 2: 1}, inplace=True)

In [61]:
iris_frame

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
52                 6.9               3.1                4.9               1.5   
53                 5.5               2.3                4.0               1.3   
54                 6.5               2.8                4.6               1.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target        name  
50        0  versicolor  
51        0  versicolor  
52        0  versicolor  
53        0  versicolor  
54        0  versicolor  
..      ...         ...  
145       1   virginica  
146       1   virginica  
147       1   virginica  
148       1   virginica  
149       1   virginica  

[100 rows x 6 columns]

In [62]:
X = iris_frame[['sepal length (cm)','sepal width (cm)','petal length (cm)', 'petal width (cm)']].to_numpy()
y = iris_frame['target'].to_numpy() #таргет
X, y

(array([[7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6

In [63]:
#нормируем
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)
X.mean(axis=0), X.std(axis=0)

(array([-6.68354261e-16,  1.62425629e-15,  3.26960681e-16, -1.44384504e-15]),
 array([1., 1., 1., 1.]))

In [64]:
#своя релизация
X = np.c_[np.ones(len(X)), X]
X

array([[ 1.        ,  1.11900931,  0.99068792, -0.25077906, -0.65303909],
       [ 1.        ,  0.20924564,  0.99068792, -0.49425387, -0.41643072],
       [ 1.        ,  0.96738203,  0.68864892, -0.00730424, -0.41643072],
       [ 1.        , -1.15539985, -1.72766308, -1.10294091, -0.88964745],
       [ 1.        ,  0.36087292, -0.21746808, -0.37251647, -0.41643072],
       [ 1.        , -0.8521453 , -0.21746808, -0.49425387, -0.88964745],
       [ 1.        ,  0.05761837,  1.29272692, -0.25077906, -0.17982236],
       [ 1.        , -2.06516352, -1.42562408, -1.95510276, -1.59947255],
       [ 1.        ,  0.5125002 ,  0.08457092, -0.37251647, -0.88964745],
       [ 1.        , -1.61028169, -0.51950708, -1.22467832, -0.65303909],
       [ 1.        , -1.91353624, -2.63378009, -1.71162795, -1.59947255],
       [ 1.        , -0.54889074,  0.38660992, -0.8594661 , -0.41643072],
       [ 1.        , -0.39726347, -2.02970209, -1.10294091, -1.59947255],
       [ 1.        , -0.24563619,  0.0

In [65]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def logloss(y, y_proba):
    logloss_1 = np.sum(np.log(y_proba[y == 1] + 1e-30))
    logloss_0 = np.sum(np.log(1 - y_proba[y == 0] + 1e-30))
    logloss_total = -(logloss_0 + logloss_1) / len(y)
    return logloss_total


def gr_logloss(X, W, y):
    y_proba = sigmoid(X @ W)
    grad = X.T @ (y_proba - y)
    return grad

In [80]:
# первоначальное точка
np.random.seed(8)
W = np.random.randn(X.shape[1])

# размер шага (learning rate)
learning_rate = 0.0015

next_W = W

# количество итерация 
n = 1001
for i in range(n):
    cur_W = next_W

    # движение в негативную сторону вычисляемого градиента
    next_W = cur_W - learning_rate * gr_logloss(X, W, y)

    if i % 5 == 0:
        print(f"Итерация: {i}")
        print(f"Текущая точка {cur_W}| Следующая точка {next_W}")
        y_proba = sigmoid(X @ next_W)
        y_class = np.where(y_proba >= 0.5, 1, 0)
        accuracy = (y_class == y).sum() / len(y)
        print(f"Logloss {logloss(y, y_proba)}")
        print(f"Accuracy {accuracy}")
        print("--------------------------------------------------------") 

Итерация: 0
Текущая точка [ 0.09120472  1.09128273 -1.94697031 -1.38634953 -2.29649157]| Следующая точка [ 0.08953198  1.16229629 -1.88378569 -1.27926621 -2.17862166]
Logloss 3.138976952645138
Accuracy 0.14
--------------------------------------------------------
Итерация: 5
Текущая точка [ 0.08284103  1.44635051 -1.63104723 -0.85093293 -1.70714202]| Следующая точка [ 0.08116829  1.51736407 -1.56786261 -0.74384961 -1.5892721 ]
Logloss 2.065077472587398
Accuracy 0.19
--------------------------------------------------------
Итерация: 10
Текущая точка [ 0.07447735  1.8014183  -1.31512415 -0.31551633 -1.11779246]| Следующая точка [ 0.07280461  1.87243185 -1.25193953 -0.20843301 -0.99992255]
Logloss 1.1936716571067874
Accuracy 0.35
--------------------------------------------------------
Итерация: 15
Текущая точка [ 0.06611366  2.15648608 -0.99920106  0.21990027 -0.5284429 ]| Следующая точка [ 0.06444093  2.22749963 -0.93601645  0.32698359 -0.41057299]
Logloss 0.6828532362194093
Accuracy 0.

In [81]:
cur_W

array([ -1.58153224,  72.10483896,  61.23764605, 105.69697091,
       115.57342009])

In [82]:
#предсказания своей модели
y_class

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [83]:
#истинные значения
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [84]:
#точность модели
accuracy

0.88